name: 'Maven Helper'
description: 'GitHub Action to retrieve useful informations from a maven project'
author: 'tobi6112'
inputs:
  pom:
    required: true
    description: 'location of the pom file that should be used to retrieve information from'
    default: './pom.xml'
outputs:
  groupId:
    description: 'the groupId property extracted from the pom file'
  artifactId:
    description: 'the artifactId property extracted from the pom file'
  version:
    description: 'the version property extracted from the pom file'
branding:
  icon: 'feather'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
